### ISSUE TITLE
module 'sqlalchemy.engine' has no attribute 'RowProxy'

### ISSUE THREAD

**Issue by gsun2unl** [LinkageIO/Camoco#99]
Traceback (most recent call last):
  File "/home/gsun2unl/miniconda3/envs/camoco/bin/camoco", line 4, in <module>
    __import__('pkg_resources').run_script('camoco==0.6.4', 'camoco')
  File "/home/gsun2unl/miniconda3/envs/camoco/lib/python3.8/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/gsun2unl/miniconda3/envs/camoco/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/home/gsun2unl/miniconda3/envs/camoco/lib/python3.8/site-packages/camoco-0.6.4-py3.8-linux-x86_64.egg/EGG-INFO/scripts/camoco", line 17, in <module>
    import camoco as co
  File "/home/gsun2unl/miniconda3/envs/camoco/lib/python3.8/site-packages/camoco-0.6.4-py3.8-linux-x86_64.egg/camoco/__init__.py", line 73, in <module>
    from .COB import COB
  File "/home/gsun2unl/miniconda3/envs/camoco/lib/python3.8/site-packages/camoco-0.6.4-py3.8-linux-x86_64.egg/camoco/COB.py", line 41, in <module>
    from odo import odo
  File "/home/gsun2unl/miniconda3/envs/camoco/lib/python3.8/site-packages/odo-0.5.0-py3.8.egg/odo/__init__.py", line 39, in <module>
    from .backends import sql
  File "/home/gsun2unl/miniconda3/envs/camoco/lib/python3.8/site-packages/odo-0.5.0-py3.8.egg/odo/backends/sql.py", line 304, in <module>
    @discover.register(sa.engine.RowProxy)
AttributeError: module 'sqlalchemy.engine' has no attribute 'RowProxy'

############## system 

System:  Distro: Ubuntu 20.04.2 LTS (Focal Fossa)

**Comment by BJ-jessica** [comment]
I also met this error.
